# Gradient Calculation with Autograd

In [1]:
# Normal torch without autograd
import torch

x = torch.rand(3)
print(x)

tensor([0.5521, 0.9454, 0.5562])


In [33]:
# Adding requires_grad=True to make it differentiable

x = torch.rand(3, requires_grad=True)
print(x)

y = x + 1
print(f'performing y = x + 1: {y}')

z = x * 2
print(f'performing z = x * 2: {z}')

z = z.mean()
print(f'Mean gradient of z:',z)

print(z.grad_fn)


tensor([0.0814, 0.4952, 0.3228], requires_grad=True)
performing y = x + 1: tensor([1.0814, 1.4952, 1.3228], grad_fn=<AddBackward0>)
performing z = x * 2: tensor([0.1629, 0.9904, 0.6457], grad_fn=<MulBackward0>)
Mean gradient of z: tensor(0.5997, grad_fn=<MeanBackward0>)


In [38]:
# How to remove the gradient in pytorch

x = torch.rand(3, requires_grad=True)

print(f'Tensor Before removing gradient : {x}')


# There are Multiple ways to remove the gradient
print('------After removing gradient ------')

# Method 1
print(x.requires_grad_(False))

# Method 2
print(x.detach())

# Method 3
with torch.no_grad():
    print(x)

Tensor Before removing gradient : tensor([0.8682, 0.6887, 0.9159], requires_grad=True)
------After removing gradient ------
tensor([0.8682, 0.6887, 0.9159])
tensor([0.8682, 0.6887, 0.9159])
tensor([0.8682, 0.6887, 0.9159])


In [60]:

weights  = torch.ones(4, requires_grad=True)


# Updating the weights using gradient

# For first Only one epoch it giving the gradient
for epoch in range(1):
    model_outputs = (weights*3).sum()
    print(model_outputs)
    model_outputs.backward()
    print(weights.grad)


# For multiple epoch it is adding the gradient to the previous gradient
print(f'--------Gradient for multiple epoch--------')
for epoch in range(2):
    model_outputs = (weights*3).sum()
    print(model_outputs)
    model_outputs.backward()
    print(f'Gradient of the weights after {epoch} epoch:',weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
--------Gradient for multiple epoch--------
tensor(12., grad_fn=<SumBackward0>)
Gradient of the weights after 0 epoch: tensor([6., 6., 6., 6.])
tensor(12., grad_fn=<SumBackward0>)
Gradient of the weights after 1 epoch: tensor([9., 9., 9., 9.])


In [64]:
# The above code is adding the gradient to the previous gradient so we need to remove the gradient after each epoch
weights = torch.ones(4, requires_grad=True)

# Removing the gradient after each epoch
print(f'--------Gradient for multiple epoch with removing gradient--------')

for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(model_output)
    print(f'Gradient of the weights after {epoch} epoch:',weights.grad)
    weights.grad.zero_() # By  changing the gradient to zero after each epoch we can avoid the adding of gradient to the previous gradient
    

--------Gradient for multiple epoch with removing gradient--------
tensor(12., grad_fn=<SumBackward0>)
Gradient of the weights after 0 epoch: tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
Gradient of the weights after 1 epoch: tensor([3., 3., 3., 3.])
