# Tensor Basics

In [3]:
# Installing pytorch

!pip3 install torch torchvision torchaudio

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/37/04/a5cd83baccbf2d4329990ec06b8abf3a644e1559a7b1f764f42d2cb77d51/torch-2.3.0-cp312-cp312-win_amd64.whl.metadata
  Using cached torch-2.3.0-cp312-cp312-win_amd64.whl.metadata (26 kB)
  Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/53/8a/864c3969af219a95213a5065d453313a96598e7c744b859e99b6ac134e16/torchvision-0.18.0-cp312-cp312-win_amd64.whl.metadata
  Using cached torchvision-0.18.0-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchaudio from https://files.pythonhosted.org/packages/f7/06/34addade5c69063d89d67ff810fd6197c28f93d9cf089c51d198562827b8/torchaudio-2.3.0-cp312-cp312-win_amd64.whl.metadata
  Using cached torchaudio-2.3.0-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/41/24/0b023b6537dfc9bae2c779353998e3e99ac7dfff42


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


###### Tensors  is a multi-dimensional matrix containing elements of a single data type. It can also be used on a GPU to accelerate computing.

In [7]:
import torch

torch.empty(1)

tensor([0.])

In [12]:
print('It creates an 2D Tensor')
x = torch.empty(1,2)
print(x)
print('It creates a tensor with the given shape, but the values are not initialized. The values are random and depend on the state of the memory.')

It creates an 2D Tensor
tensor([[inf, 0.]])
It creates a tensor with the given shape, but the values are not initialized. The values are random and depend on the state of the memory.


In [13]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [17]:
torch.zeros(4,2, dtype = torch.int)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [18]:
# Another Way to create a tensor
torch.tensor([2,3,4])

tensor([2, 3, 4])

In [19]:
# Check the size of Tensor
x = torch.tensor([2,3,4])
x.size()

torch.Size([3])

In [25]:
# Perform operations on Tensors

x = torch.tensor([2,3,4])
y = torch.tensor([1,2,3])

z = x + y # It will do element wise addition
print(z)

inplace_addition = x.add_(y) # It will do inplace addition
print(f'inplace_addition: {inplace_addition}')  # Anything with underscore is inplace operation

tensor([3, 5, 7])
inplace_addition: tensor([3, 5, 7])


In [26]:
#  It will do element wise subtraction
x = torch.tensor([2,1,4])
y = torch.tensor([1,2,3])

z = x - y 
print(z)

inplace_subtraction = x.sub_(y) # It will do inplace subtraction
print(f'inplace_subtraction: {inplace_subtraction}')  # Anything with underscore is inplace operation

tensor([ 1, -1,  1])
inplace_subtraction: tensor([ 1, -1,  1])


In [29]:
# It will do element wise multiplication

x = torch.tensor([2,1,4]) 
y = torch.tensor([1,2,3])

z = x * y
print(z)

inplace_multiplication = x.mul_(y) # It will do inplace multiplication
print(f'inplace_multiplication: {inplace_multiplication}')  # Anything with underscore is inplace operation

tensor([ 2,  2, 12])
inplace_multiplication: tensor([ 2,  2, 12])


In [52]:
# It will do element wise division

x = torch.tensor([2,1,4], dtype=float)
y = torch.randint(1, 10, size=x.size(), dtype=float)  # Specify the high argument for torch.randint()

z = x/y
print(z)

inplace_division = x.div_(y) # It will do inplace division
print(f'inplace_division: {inplace_division}')  # Anything with underscore is inplace operation

tensor([0.2857, 0.5000, 1.3333], dtype=torch.float64)
inplace_division: tensor([0.2857, 0.5000, 1.3333], dtype=torch.float64)


In [70]:
x = torch.rand(5,3)
print(x)

# Slicing the tensor syntax is same as numpy array slicing

print(x[:,0]) # It will give the first column
print(x[0,:]) # It will give the first row

print(x[:,1:2]) # It will give the second column

print(x[1,1].item()) # It will give the value at 1,1 index. It will only work for one number for multiple numbers use x[1,1].tolist()

tensor([[0.3840, 0.2079, 0.7426],
        [0.2038, 0.8460, 0.4431],
        [0.5505, 0.2135, 0.5048],
        [0.9269, 0.8213, 0.6684],
        [0.6727, 0.7803, 0.7511]])
tensor([0.3840, 0.2038, 0.5505, 0.9269, 0.6727])
tensor([0.3840, 0.2079, 0.7426])
tensor([[0.2079],
        [0.8460],
        [0.2135],
        [0.8213],
        [0.7803]])
tensor(0.8460)


In [74]:
# View function is used to reshape the tensor to different shape but the number of elements should be same in both the shapes.

x = torch.rand(4,4)
y = x.view(16) # it has transformed the 4x4 tensor to 16x1 tensor

print(f'reshape the tensor: {y}') 

#Use -1 to infer the shape of the tensor automatically
y = x.view(-1,8) # it has transformed the 4x4 tensor to 2x8 tensor
print(f'reshape the tensor: {y}')

reshape the tensor: tensor([0.6861, 0.0680, 0.9674, 0.3410, 0.9940, 0.5120, 0.6434, 0.8760, 0.8992,
        0.0856, 0.1700, 0.4217, 0.1166, 0.8901, 0.6700, 0.2268])
reshape the tensor: tensor([[0.6861, 0.0680, 0.9674, 0.3410, 0.9940, 0.5120, 0.6434, 0.8760],
        [0.8992, 0.0856, 0.1700, 0.4217, 0.1166, 0.8901, 0.6700, 0.2268]])


In [78]:
# change numpy array to tensor

import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

print(f'Original numpy array: {a}')
print(f'change numpy array to tensor: {b}')

Original numpy array: [1. 1. 1. 1. 1.]
change numpy array to tensor: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [81]:
# change tensor to numpy array
a = torch.rand(5,2)
print(f'Original tensor: {a}')

b = a.numpy()
print(f'change tensor to numpy array: {b}, type: {type(b)}')

Original tensor: tensor([[0.8337, 0.6743],
        [0.2616, 0.4905],
        [0.0151, 0.1021],
        [0.7541, 0.9332],
        [0.6730, 0.9271]])
change tensor to numpy array: [[0.8337192  0.67425394]
 [0.2616135  0.49046916]
 [0.01508915 0.10206342]
 [0.7541462  0.9332395 ]
 [0.6729545  0.9270863 ]], type: <class 'numpy.ndarray'>


In [82]:
# Check GPU is available or not

print(f'GPU is available: {torch.cuda.is_available()}')

GPU is available: False


In [86]:
# If GPU is available then move the tensor to GPU

if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))
else:
    print(f'GPU not available performing on CPU')
    x = torch.ones(5)
    y = torch.ones(5)
    z = x + y
    print(z)

GPU not available performing on CPU
tensor([2., 2., 2., 2., 2.])
